# Generated by Django 2.2.6 on 2019-10-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='body',
            field=models.TextField(default='Add a body'),
            preserve_default=False,
        ),
    ]
