# Generated by Django 2.2.6 on 2019-10-31 00:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0002_newsitem_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('prep_time', models.CharField(max_length=50)),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='NewsItem',
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipebox.Author'),
        ),
    ]
