# Generated by Django 2.2.6 on 2019-11-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0003_auto_20191031_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitem',
            name='post_date',
            field=models.DateTimeField(null=True),
        ),
    ]
