# Generated by Django 2.2.6 on 2019-11-04 15:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0004_recipeitem_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='post_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 4, 15, 37, 0, 932697, tzinfo=utc)),
        ),
    ]
