# Generated by Django 2.2.6 on 2019-11-04 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0006_auto_20191104_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
