# Generated by Django 2.2.6 on 2019-11-07 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipebox', '0007_auto_20191104_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='User',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default='empty', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='prep_time',
            field=models.CharField(default='empty', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='title',
            field=models.CharField(default='empty', max_length=50),
        ),
    ]
